version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - eval $(aws ecr get-login --no-include-email | sed 's|https://||')
      - aws --version
      - REPOSITORY_URI=083869532453.dkr.ecr.eu-west-1.amazonaws.com/oqeilat-bot-dashboard
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - docker pull $REPOSITORY_URI:latest || true
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --tag $REPOSITORY_URI:latest .
      - docker images
  post_build:
    commands:
      - echo Build completed on `date` 
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"OQ-APP-TEST-Frontend-Container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json